using System;
using LiteDB;
using System.Collections.Generic; // Required for using collections such as List
namespace Blog.Models.Repos
{
    public class BlogRepo : IDisposable
    {
        public LiteDatabase DB { get; set; }
        public LiteCollection<Post> Posts { get; set; }


        public BlogRepo()
        {
            DB = new LiteDatabase(@"Data/Blog.db");
            Posts = (LiteCollection<Post>)DB.GetCollection<Post>("posts");
        }

        // Implementar Dispose para liberar la base de datos
        public void Dispose()
        {
            DB?.Dispose();
        }

        public void CreateExamplePosts()
        {

            List<Post> PostList = new List<Post>(){
                new Post(){
                    Title = "First post",
                    Public = true,
                    CoverImagePath = "", // leave this blank for now
                    Excerpt = "Define the underlying",
                    Content = "Define the underlying principles that drive decisions and strategy for your design language bleeding edge onward and upward"
                    // The above text was generated by Office Ipsum http://officeipsum.com/index.php
                },
                new Post(){
                    Title = "Second post",
                    Public = true,
                    CoverImagePath = "", // still blank
                    Excerpt = "so what's our",
                    Content = "so what's our go to market strategy?. Customer centric all hands on deck yet where the metal hits the meat define"
                },
                new Post(){
                    Title = "Not visible",
                    Public = false,
                    CoverImagePath = "", // blank
                    Excerpt = "not important",
                    Content = "not important, you should not see this post"
                },
                new Post(){
                    Title = "Third post",
                    Public = true,
                    CoverImagePath = "", // blank
                    Excerpt = "the underlying",
                    Content = "the underlying principles that drive decisions and strategy for your design language not the long pole",
                    Deleted = true // this one should also not be visible
                },
                new Post(){
                    Title = "Fourth post",
                    Public = true,
                    CoverImagePath = "", // blank
                    Excerpt = "in the future",
                    Content = "Post scheduling made super easy",
                    Created = DateTime.Now.AddDays(3) // Post scheduling made easy
                },
                new Post(){
                    Title = "Markdown Test",
                    Public = true,
                    CoverImagePath = "", // blank
                    Excerpt = "Let's see what markdown can do",
                    Content =   "# Hello world\n"+
                                "**Lorem** ipsum dolor sit"+
                                "amet, *consectetur* adipiscing elit. Sed"+
                                "eu est nec metus luctus tempus. Pellentesque"+
                                "at elementum sapien, ac faucibus sem"+
                                "![surprise](https://media.giphy.com/media/fdyZ3qI0GVZC0/giphy.gif)"
                },
            };
            try
            {
                // This will ensure that the title of the post is unique
                // since we're going to be using it later in the URL
                Posts.EnsureIndex(p => p.Title, true);

                Posts.EnsureIndex(p => p._id, true);
                // Finally let's insert all these posts into the database
                Posts.InsertBulk(PostList);
            }
            catch (LiteDB.LiteException ex)
            {
                // we'll simply ignore any exceptions that might happen
            }
        }
    }
}